### ISSUE TITLE
1.4 Roadmap

### ISSUE THREAD

**Issue by mensfeld** [karafka/karafka#602]
Params as a hash make it problematic to abstract division in between params metadata and the payload. While we already have payload as a separate entity, the same should happen with metadata. That way we can access and operate on metadata without forcing deserialization of the payload.

I have a POC for `2.0` with this, but due to https://github.com/karafka/karafka/pull/599#issuecomment-678447151 I want to backport it and release `1.4`.

- [x] Rename `Karafka::Params::Metadata` to `Karafka::Params::BatchMetadata` (https://github.com/karafka/karafka/pull/603)
- [x] Separate metadata (including Karafka native metadata) from the root of params (https://github.com/karafka/karafka/pull/604)
- [x] Add missing specs to params metadata (https://github.com/karafka/karafka/pull/604)
- [x] Remove metadata hash dependency
- [x] Remove params dependency on a hash in favour of PORO (https://github.com/karafka/karafka/pull/604)
- [x] Remove batch metadata dependency on a hash  (https://github.com/karafka/karafka/pull/604)
- [x] Remove MultiJson in favour of JSON (ref https://github.com/karafka/karafka/issues/605)
- [x] Release Waterdrop 1.4
- [x] Update example-app and check the touched components (especially manual offset management)
- [x] Update the karafka-testing lib
- [x] Update the sidekiq-backend
- [x] Release `1.4-alpha`
- [x] Release `1.4-rc1`
- [x] Prepare release notes
- [x] Update wiki
- [x] Release `1.4`
